// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForCreateProductsBatch implements pgx.CopyFromSource.
type iteratorForCreateProductsBatch struct {
	rows                 []CreateProductsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateProductsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateProductsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ProdcName,
		r.rows[0].ProdcPrice,
		r.rows[0].StockOnHand,
		r.rows[0].ExpiryDate,
	}, nil
}

func (r iteratorForCreateProductsBatch) Err() error {
	return nil
}

// (This tells sqlc to generate a function that accepts a slice of products)
func (q *Queries) CreateProductsBatch(ctx context.Context, arg []CreateProductsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"products"}, []string{"prodc_name", "prodc_price", "stock_on_hand", "expiry_date"}, &iteratorForCreateProductsBatch{rows: arg})
}
