// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    cust_name, cust_email, cust_address, password_hash
) VALUES (
    $1, $2, $3, $4
)
RETURNING cust_id, cust_name, cust_email, cust_address, password_hash, is_admin
`

type CreateCustomerParams struct {
	CustName     string `json:"cust_name"`
	CustEmail    string `json:"cust_email"`
	CustAddress  string `json:"cust_address"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.CustName,
		arg.CustEmail,
		arg.CustAddress,
		arg.PasswordHash,
	)
	var i Customer
	err := row.Scan(
		&i.CustID,
		&i.CustName,
		&i.CustEmail,
		&i.CustAddress,
		&i.PasswordHash,
		&i.IsAdmin,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers WHERE cust_id = $1
`

// Because we set ON DELETE CASCADE, this automatically wipes their orders too!
func (q *Queries) DeleteCustomer(ctx context.Context, custID int64) error {
	_, err := q.db.Exec(ctx, deleteCustomer, custID)
	return err
}

const getCustomer = `-- name: GetCustomer :one
SELECT cust_id, cust_name, cust_email, cust_address, password_hash, is_admin FROM customers WHERE cust_id = $1 LIMIT 1
`

func (q *Queries) GetCustomer(ctx context.Context, custID int64) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, custID)
	var i Customer
	err := row.Scan(
		&i.CustID,
		&i.CustName,
		&i.CustEmail,
		&i.CustAddress,
		&i.PasswordHash,
		&i.IsAdmin,
	)
	return i, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT cust_id, cust_name, cust_email, cust_address, password_hash, is_admin FROM customers WHERE cust_email = $1 LIMIT 1
`

// Essential for the JWT Login process
func (q *Queries) GetCustomerByEmail(ctx context.Context, custEmail string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmail, custEmail)
	var i Customer
	err := row.Scan(
		&i.CustID,
		&i.CustName,
		&i.CustEmail,
		&i.CustAddress,
		&i.PasswordHash,
		&i.IsAdmin,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT cust_id, cust_name, cust_email, cust_address, password_hash, is_admin FROM customers 
ORDER BY cust_id DESC 
LIMIT $1 OFFSET $2
`

type ListCustomersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Used for the Admin Dashboard to view all registered users with pagination
func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.CustID,
			&i.CustName,
			&i.CustEmail,
			&i.CustAddress,
			&i.PasswordHash,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCustomers = `-- name: SearchCustomers :many
SELECT cust_id, cust_name, cust_email, cust_address, password_hash, is_admin FROM customers 
WHERE ($3::text IS NULL OR 
       cust_name ILIKE '%' || $3 || '%' OR 
       cust_email ILIKE '%' || $3 || '%')
ORDER BY cust_id DESC
LIMIT $1 OFFSET $2
`

type SearchCustomersParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	SearchTerm pgtype.Text `json:"search_term"`
}

// Allows an admin to quickly find a user by typing part of their name or email
func (q *Queries) SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, searchCustomers, arg.Limit, arg.Offset, arg.SearchTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.CustID,
			&i.CustName,
			&i.CustEmail,
			&i.CustAddress,
			&i.PasswordHash,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerEmail = `-- name: UpdateCustomerEmail :exec
UPDATE customers 
SET cust_email = $2 
WHERE cust_id = $1
`

type UpdateCustomerEmailParams struct {
	CustID    int64  `json:"cust_id"`
	CustEmail string `json:"cust_email"`
}

func (q *Queries) UpdateCustomerEmail(ctx context.Context, arg UpdateCustomerEmailParams) error {
	_, err := q.db.Exec(ctx, updateCustomerEmail, arg.CustID, arg.CustEmail)
	return err
}

const updateCustomerPassword = `-- name: UpdateCustomerPassword :exec
UPDATE customers 
SET password_hash = $2 
WHERE cust_id = $1
`

type UpdateCustomerPasswordParams struct {
	CustID       int64  `json:"cust_id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateCustomerPassword(ctx context.Context, arg UpdateCustomerPasswordParams) error {
	_, err := q.db.Exec(ctx, updateCustomerPassword, arg.CustID, arg.PasswordHash)
	return err
}

const updateCustomerProfile = `-- name: UpdateCustomerProfile :exec
UPDATE customers 
SET cust_name = $2, cust_address = $3 
WHERE cust_id = $1
`

type UpdateCustomerProfileParams struct {
	CustID      int64  `json:"cust_id"`
	CustName    string `json:"cust_name"`
	CustAddress string `json:"cust_address"`
}

func (q *Queries) UpdateCustomerProfile(ctx context.Context, arg UpdateCustomerProfileParams) error {
	_, err := q.db.Exec(ctx, updateCustomerProfile, arg.CustID, arg.CustName, arg.CustAddress)
	return err
}
