// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	CustID       int64  `json:"cust_id"`
	CustName     string `json:"cust_name"`
	CustEmail    string `json:"cust_email"`
	CustAddress  string `json:"cust_address"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      bool   `json:"is_admin"`
}

type Order struct {
	ID        int64              `json:"id"`
	CustID    int64              `json:"cust_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OrderItem struct {
	OrderID    int64 `json:"order_id"`
	ProdcID    int64 `json:"prodc_id"`
	Quantity   int32 `json:"quantity"`
	TotalPrice int32 `json:"total_price"`
}

type Product struct {
	ID          int64       `json:"id"`
	ProdcName   string      `json:"prodc_name"`
	ProdcPrice  int32       `json:"prodc_price"`
	StockOnHand int32       `json:"stock_on_hand"`
	ExpiryDate  pgtype.Date `json:"expiry_date"`
}

type ProductInventory struct {
	ProductID          int64       `json:"product_id"`
	ProdcName          string      `json:"prodc_name"`
	StockOnHand        int32       `json:"stock_on_hand"`
	TotalOrdered       interface{} `json:"total_ordered"`
	AvailableInventory int32       `json:"available_inventory"`
}
