// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package store

import (
	"context"
)

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (
    order_id, prodc_id, quantity, total_price
) VALUES (
    $1, $2, $3, $4
)
`

type CreateOrderItemParams struct {
	OrderID    int64 `json:"order_id"`
	ProdcID    int64 `json:"prodc_id"`
	Quantity   int32 `json:"quantity"`
	TotalPrice int32 `json:"total_price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.OrderID,
		arg.ProdcID,
		arg.Quantity,
		arg.TotalPrice,
	)
	return err
}

const listOrderItemsWithProductDetails = `-- name: ListOrderItemsWithProductDetails :many
SELECT 
    oi.order_id, 
    oi.prodc_id, 
    oi.quantity, 
    oi.total_price AS purchased_price_cents,
    p.prodc_name
FROM order_items oi
JOIN products p ON oi.prodc_id = p.id
WHERE oi.order_id = $1
`

type ListOrderItemsWithProductDetailsRow struct {
	OrderID             int64  `json:"order_id"`
	ProdcID             int64  `json:"prodc_id"`
	Quantity            int32  `json:"quantity"`
	PurchasedPriceCents int32  `json:"purchased_price_cents"`
	ProdcName           string `json:"prodc_name"`
}

// Joins the items with the products table so the frontend gets the name and historical price
func (q *Queries) ListOrderItemsWithProductDetails(ctx context.Context, orderID int64) ([]ListOrderItemsWithProductDetailsRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsWithProductDetails, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsWithProductDetailsRow
	for rows.Next() {
		var i ListOrderItemsWithProductDetailsRow
		if err := rows.Scan(
			&i.OrderID,
			&i.ProdcID,
			&i.Quantity,
			&i.PurchasedPriceCents,
			&i.ProdcName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
