// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package store

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    cust_id, status
) VALUES (
    $1, $2
)
RETURNING id, cust_id, status, created_at
`

type CreateOrderParams struct {
	CustID int64  `json:"cust_id"`
	Status string `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.CustID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, cust_id, status, created_at FROM orders WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomerOrders = `-- name: ListCustomerOrders :many
SELECT id, cust_id, status, created_at FROM orders 
WHERE cust_id = $1 
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCustomerOrdersParams struct {
	CustID int64 `json:"cust_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Get a user's order history, newest first, with pagination
func (q *Queries) ListCustomerOrders(ctx context.Context, arg ListCustomerOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listCustomerOrders, arg.CustID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders 
SET status = $2 
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

// Used by admins to mark orders as 'shipped' or 'cancelled'
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
