// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProductStock = `-- name: AddProductStock :exec
UPDATE products 
SET stock_on_hand = stock_on_hand + $2 
WHERE id = $1
`

type AddProductStockParams struct {
	ID          int64 `json:"id"`
	StockOnHand int32 `json:"stock_on_hand"`
}

// Atomic update: Safe from race conditions when two admins add stock at the same time
func (q *Queries) AddProductStock(ctx context.Context, arg AddProductStockParams) error {
	_, err := q.db.Exec(ctx, addProductStock, arg.ID, arg.StockOnHand)
	return err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    prodc_name, prodc_price, stock_on_hand, expiry_date
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, prodc_name, prodc_price, stock_on_hand, expiry_date
`

type CreateProductParams struct {
	ProdcName   string      `json:"prodc_name"`
	ProdcPrice  int32       `json:"prodc_price"`
	StockOnHand int32       `json:"stock_on_hand"`
	ExpiryDate  pgtype.Date `json:"expiry_date"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ProdcName,
		arg.ProdcPrice,
		arg.StockOnHand,
		arg.ExpiryDate,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProdcName,
		&i.ProdcPrice,
		&i.StockOnHand,
		&i.ExpiryDate,
	)
	return i, err
}

type CreateProductsBatchParams struct {
	ProdcName   string      `json:"prodc_name"`
	ProdcPrice  int32       `json:"prodc_price"`
	StockOnHand int32       `json:"stock_on_hand"`
	ExpiryDate  pgtype.Date `json:"expiry_date"`
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, prodc_name, prodc_price, stock_on_hand, expiry_date FROM products WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProdcName,
		&i.ProdcPrice,
		&i.StockOnHand,
		&i.ExpiryDate,
	)
	return i, err
}

const getProductInventory = `-- name: GetProductInventory :one
SELECT product_id, prodc_name, stock_on_hand, total_ordered, available_inventory FROM product_inventory WHERE product_id = $1 LIMIT 1
`

// Queries the View we created to get real-time available stock
func (q *Queries) GetProductInventory(ctx context.Context, productID int64) (ProductInventory, error) {
	row := q.db.QueryRow(ctx, getProductInventory, productID)
	var i ProductInventory
	err := row.Scan(
		&i.ProductID,
		&i.ProdcName,
		&i.StockOnHand,
		&i.TotalOrdered,
		&i.AvailableInventory,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, prodc_name, prodc_price, stock_on_hand, expiry_date FROM products 
ORDER BY id DESC 
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Includes Pagination
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProdcName,
			&i.ProdcPrice,
			&i.StockOnHand,
			&i.ExpiryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByIDs = `-- name: ListProductsByIDs :many
SELECT id, prodc_name, prodc_price, stock_on_hand, expiry_date FROM products WHERE id = ANY($1)
`

func (q *Queries) ListProductsByIDs(ctx context.Context, id int64) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProdcName,
			&i.ProdcPrice,
			&i.StockOnHand,
			&i.ExpiryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, prodc_name, prodc_price, stock_on_hand, expiry_date FROM products 
WHERE ($3::text IS NULL OR prodc_name ILIKE '%' || $3 || '%')
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type SearchProductsParams struct {
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	NameQuery pgtype.Text `json:"name_query"`
}

// Dynamic search using sqlc.narg() + Pagination
func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, searchProducts, arg.Limit, arg.Offset, arg.NameQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProdcName,
			&i.ProdcPrice,
			&i.StockOnHand,
			&i.ExpiryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductName = `-- name: UpdateProductName :exec
UPDATE products 
SET prodc_name = $2 
WHERE id = $1
`

type UpdateProductNameParams struct {
	ID        int64  `json:"id"`
	ProdcName string `json:"prodc_name"`
}

func (q *Queries) UpdateProductName(ctx context.Context, arg UpdateProductNameParams) error {
	_, err := q.db.Exec(ctx, updateProductName, arg.ID, arg.ProdcName)
	return err
}

const updateProductPrice = `-- name: UpdateProductPrice :exec
UPDATE products 
SET prodc_price = $2 
WHERE id = $1
`

type UpdateProductPriceParams struct {
	ID         int64 `json:"id"`
	ProdcPrice int32 `json:"prodc_price"`
}

func (q *Queries) UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) error {
	_, err := q.db.Exec(ctx, updateProductPrice, arg.ID, arg.ProdcPrice)
	return err
}

const updateProductStock = `-- name: UpdateProductStock :exec
UPDATE products 
SET stock_on_hand = $2 
WHERE id = $1
`

type UpdateProductStockParams struct {
	ID          int64 `json:"id"`
	StockOnHand int32 `json:"stock_on_hand"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error {
	_, err := q.db.Exec(ctx, updateProductStock, arg.ID, arg.StockOnHand)
	return err
}
